os: linux
dist: trusty
sudo: required
script: bash ./.travis-ci/run.sh
env:
  global:
    secure: IjSRPs+trUMZ5YXsmPPWsw9vK6WFJvWL58gXn3tp1jiWjHmCBbbX82r8vzQYvzQnqRztFkvUK0tD8eQguA0+79J2jV+78HpIABJ+Q6yNmpo5RwBZ5vtUkIlFfrdZVqTncWOQcUugDFkcIoe+lmx0G6B/mNeih/CNeRyPe4UNK7d+8UGOPagj6Gq6WWR71DnqCgMKfmOi08eMuwul+HumZGs6qTay3zVJZJTrv3haCu+3bI8EnzkM7URbFqdJ6mPQQxC7IFne75GeaRA416/DXbA8hMlwFIztOtqTwMbVRL06w+GUZScdbFlmn41XhqVvel3+URQwXiqxbsjlH2cb/9UhKKVg/947G7hh8BwoieUZwAFNf5XMYBiKESyqmbJ+VnQeHr4iZJbA88KP8ckX7He9luIs2utOH5D+19e9RzjBW1WDYSa24ksloYa5EmEztgC4XeU29f6UCPu9xdlFymTgcJTKX7utZMcepcFD92SNdKMmmEAGBECwqSXZKkPGPrQ0KtdomtiLIr0T+a3EzTbPIpVoOmepP2pfo5zf8rYfCNstrfV/SBL71DWK1x92mB1+e5Pq2i3tThcdOfSON3JANHibxfIl8tlyjtjOjfAeber7x1uEQucj1lXRO4996hapgxqVX0KgGEu0DDtv4l89ixYBLA9OHV/6stYjYYA=
